"""
Django settings for Gestion_edt project.

Generated by 'django-admin startproject' using Django 6.0.2.

Toute valeur sensible ou dépendante de l'environnement (clé secrète, base de
données, hôtes autorisés, origines CORS/CSRF) est lue depuis les variables
d'environnement, ou depuis un fichier `.env` à la racine du projet (jamais
versionné — voir `.env.example` pour la liste complète).

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import environ
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')

# Par défaut, on est en mode PRODUCTION : il faut demander explicitement le
# mode développement (DJANGO_DEBUG=True dans le .env local).
DEBUG = env.bool('DJANGO_DEBUG', default=False)

# HTTPS : activé par défaut hors debug. À passer à False uniquement pour une
# démo derrière un tunnel qui ne transmet pas X-Forwarded-Proto (sinon la
# redirection SSL boucle).
HTTPS_ENABLED = env.bool('DJANGO_HTTPS', default=not DEBUG)

# La clé secrète signe aussi les jetons JWT (SIGNING_KEY ci-dessous) : qui la
# connaît peut fabriquer un jeton valide pour n'importe quel compte.
SECRET_KEY = env.str('DJANGO_SECRET_KEY', default='')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY est obligatoire quand DJANGO_DEBUG n'est pas True. "
            "Générez-en une avec : python -c \"from django.core.management.utils "
            "import get_random_secret_key; print(get_random_secret_key())\""
        )
    SECRET_KEY = 'dev-only-insecure-key-do-not-use-outside-local-development'

ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'EDT_app',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders'
]

REST_FRAMEWORK = {
    # JWT comme mécanisme d'authentification par défaut
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    # Toute vue exige une authentification sauf surcharge explicite
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Pagination par défaut sur toutes les listes
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # Convertit toute django.core.exceptions.ValidationError non interceptée
    # en réponse 400 DRF au lieu d'un 500 (cf. EDT_app/exception_handlers.py).
    'EXCEPTION_HANDLER': 'EDT_app.exception_handlers.exception_handler',
    # Format de date cohérent avec les modèles Django
    'DATE_FORMAT'     : '%Y-%m-%d',
    'DATETIME_FORMAT' : '%Y-%m-%dT%H:%M:%S',
    'TIME_FORMAT'     : '%H:%M',
    # Limitation de débit. Les scopes 'login' et 'login_ip' sont utilisés par
    # EDT_app/throttles.py (POST /api/token/) ; 'anon' et 'user' s'appliquent
    # à toutes les autres vues. 'user' est généreux : une page du frontend
    # enchaîne facilement 10 à 20 requêtes (listes paginées, listes en cascade).
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/min',
        'user': '600/min',
        'login': '5/min',
        'login_ip': '120/min',
    },
    # Nombre de reverse proxies devant Django (Nginx = 1) : DRF lit alors la
    # vraie adresse du client dans X-Forwarded-For au lieu de voir 127.0.0.1
    # pour tout le monde. Nginx doit ÉCRASER cet en-tête (voir DEPLOIEMENT.md).
    'NUM_PROXIES': env.int('DJANGO_NUM_PROXIES', default=1 if HTTPS_ENABLED else 0),
}

# Les compteurs de limitation de débit vivent dans le cache. Le cache mémoire
# par défaut est propre à chaque processus : avec plusieurs workers Gunicorn,
# chacun aurait son propre compteur et la limite réelle serait multipliée.
# En production on utilise donc un cache fichier partagé par tous les workers.
if DEBUG:
    CACHES = {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
            'LOCATION': env.str('DJANGO_CACHE_DIR', default=str(BASE_DIR / 'cache')),
        }
    }

# L'API navigable (formulaires HTML auto-générés) n'a sa place qu'en développement.
if not DEBUG:
    REST_FRAMEWORK['DEFAULT_RENDERER_CLASSES'] = [
        'rest_framework.renderers.JSONRenderer',
    ]

SIMPLE_JWT = {
    # Durée de vie du token d'accès : courte, car un jeton volé reste utilisable
    # jusqu'à son expiration. Le frontend le renouvelle tout seul (client.js).
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    # Durée de vie du token de rafraîchissement : 1 jour, renouvelée à chaque
    # rafraîchissement (rotation) : une session active reste ouverte, une
    # session abandonnée expire.
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    # Génère un nouveau refresh token à chaque refresh (rotation)
    'ROTATE_REFRESH_TOKENS': True,
    # Ajoute l'ancien refresh token à la blacklist après rotation
    'BLACKLIST_AFTER_ROTATION': True,
    # Algorithme de signature
    'ALGORITHM': 'HS256',
    # Clé de signature — utilise SECRET_KEY du projet
    'SIGNING_KEY': SECRET_KEY,
    # Préfixe attendu dans le header Authorization
    'AUTH_HEADER_TYPES': ('Bearer',),
    # Champ utilisé comme identifiant dans le payload
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    # Classe du token — on garde la valeur par défaut
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # django-cors-headers doit passer avant tout middleware qui peut produire
    # une réponse (CommonMiddleware : redirection APPEND_SLASH), sinon ces
    # réponses partent sans en-têtes CORS.
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Gestion_edt.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Gestion_edt.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Utilisez un compte MySQL dédié à l'application (droits limités à cette base),
# jamais `root`.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env.str('DB_NAME', default='edt_uccb'),
        'USER': env.str('DB_USER'),
        'PASSWORD': env.str('DB_PASSWORD'),
        'HOST': env.str('DB_HOST', default='localhost'),
        'PORT': env.str('DB_PORT', default='3306'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 10},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# Destination de `collectstatic`, servie directement par Nginx en production.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Origines autorisées à appeler l'API depuis un navigateur (front Vite en dev,
# domaine réel en production).
CORS_ALLOWED_ORIGINS = env.list(
    'DJANGO_CORS_ALLOWED_ORIGINS',
    default=['http://localhost:3000', 'http://127.0.0.1:3000'],
)

CSRF_TRUSTED_ORIGINS = env.list(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    default=['http://localhost:3000', 'http://127.0.0.1:3000'],
)

# Rappel : Ceci doit toujours être à True
CORS_ALLOW_CREDENTIALS = True

# Media files (Profile pictures, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = env.str('DJANGO_MEDIA_ROOT', default=os.path.join(BASE_DIR, 'media'))

# Documents pédagogiques : taille maximale d'un fichier (à garder alignée sur
# `client_max_body_size` de Nginx et sur TAILLE_MAX_MO dans DocumentsPage.jsx).
DOCUMENT_MAX_UPLOAD_BYTES = 20 * 1024 * 1024

# Les documents ne sont jamais servis par une URL /media/ publique : ils
# passent par GET /api/documents/<id>/telecharger/, qui vérifie les droits.
# En production, Django répond alors avec X-Accel-Redirect vers cet emplacement
# Nginx `internal` (voir DEPLOIEMENT.md) ; vide (développement), Django envoie
# lui-même le fichier.
PROTECTED_MEDIA_INTERNAL_PREFIX = env.str('DJANGO_PROTECTED_MEDIA_PREFIX', default='')

# ──────────────────────────────────────────────────────────────────────────────
# Durcissement HTTPS (actif dès que HTTPS_ENABLED)
# ──────────────────────────────────────────────────────────────────────────────
if HTTPS_ENABLED:
    # Nginx (ou tout reverse proxy TLS) doit poser X-Forwarded-Proto en
    # ÉCRASANT toute valeur envoyée par le client, et Gunicorn ne doit écouter
    # que sur localhost / une socket, jamais directement sur Internet.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    # Démarrer bas (1 h) puis monter (1 an) une fois HTTPS confirmé stable :
    # HSTS est mémorisé par les navigateurs et ne se défait pas côté serveur.
    SECURE_HSTS_SECONDS = env.int('DJANGO_HSTS_SECONDS', default=3600)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool('DJANGO_HSTS_INCLUDE_SUBDOMAINS', default=False)
    SECURE_HSTS_PRELOAD = False
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'

# ──────────────────────────────────────────────────────────────────────────────
# Journalisation : en production, les erreurs vont dans un fichier tournant côté
# serveur (le client ne reçoit qu'une réponse générique). Ne jamais y écrire de
# mots de passe ni de jetons.
# ──────────────────────────────────────────────────────────────────────────────
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
}

if not DEBUG:
    LOG_DIR = Path(env.str('DJANGO_LOG_DIR', default=str(BASE_DIR / 'logs')))
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    LOGGING['handlers']['fichier_erreurs'] = {
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': str(LOG_DIR / 'django.log'),
        'maxBytes': 5 * 1024 * 1024,
        'backupCount': 5,
        'formatter': 'standard',
        'encoding': 'utf-8',
    }
    LOGGING['root']['handlers'] = ['console', 'fichier_erreurs']
