"""
Django settings for Gestion_edt project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bm4l@%-r-36nwnwhh3(th&w9k8y4tna*odmp8xxaa#*f()tkgc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'EDT_app',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders'
]

REST_FRAMEWORK = {
    # JWT comme mécanisme d'authentification par défaut
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    # Toute vue exige une authentification sauf surcharge explicite
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Pagination par défaut sur toutes les listes
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # Format de date cohérent avec les modèles Django
    'DATE_FORMAT'     : '%Y-%m-%d',
    'DATETIME_FORMAT' : '%Y-%m-%dT%H:%M:%S',
    'TIME_FORMAT'     : '%H:%M',
}

from datetime import timedelta

SIMPLE_JWT = {
    # Durée de vie du token d'accès : 8h (une journée de travail)
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),
    # Durée de vie du token de rafraîchissement : 7 jours
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    # Génère un nouveau refresh token à chaque refresh (rotation)
    'ROTATE_REFRESH_TOKENS': True,
    # Ajoute l'ancien refresh token à la blacklist après rotation
    'BLACKLIST_AFTER_ROTATION': True,
    # Algorithme de signature
    'ALGORITHM': 'HS256',
    # Clé de signature — utilise SECRET_KEY du projet
    'SIGNING_KEY': SECRET_KEY,
    # Préfixe attendu dans le header Authorization
    'AUTH_HEADER_TYPES': ('Bearer',),
    # Champ utilisé comme identifiant dans le payload
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    # Classe du token — on garde la valeur par défaut
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'Gestion_edt.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Gestion_edt.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'edt_uccb',
        'USER': 'root',  # votre utilisateur MySQL
        'PASSWORD': 'carlinob1',  # votre mot de passe MySQL
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Autorise les requêtes provenant de votre Vite sur le port 3000
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# Indispensable pour autoriser le passage du cookie CSRF depuis ce port
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# Rappel : Ceci doit toujours être à True
CORS_ALLOW_CREDENTIALS = True