# Generated by Django 6.0.2 on 2026-05-08 16:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('active', 'Active'), ('archivée', 'Archivée')], default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu')], default='actif', max_length=10)),
                ('motif_suspension', models.TextField(blank=True, help_text="Obligatoire si le statut est 'Suspendu'. Ex: En déplacement, Congé maladie, etc.")),
            ],
        ),
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='EDT_app.profil')),
                ('grade', models.CharField(blank=True, choices=[('', '----------'), ('Ingénieur', 'Ingénieur'), ('Docteur', 'Docteur'), ('Professeur', 'Professeur')], max_length=50)),
                ('contrat', models.CharField(choices=[('Permanent', 'Permanent'), ('Vacataire', 'Vacataire')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='EDT_app.faculte')),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='EDT_app.departement')),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matieres', to='EDT_app.departement')),
            ],
            options={
                'unique_together': {('libelle', 'departement')},
            },
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_parcours', models.CharField(choices=[('Licence', 'Licence'), ('Master', 'Master'), ('Doctorat', 'Doctorat')], max_length=20)),
                ('niveau', models.IntegerField()),
            ],
            options={
                'unique_together': {('type_parcours', 'niveau')},
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(choices=[('Semestre 1', 'Semestre 1'), ('Semestre 2', 'Semestre 2')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='EDT_app.anneeacademique')),
            ],
            options={
                'unique_together': {('libelle', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('credits', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Un module doit avoir au moins 1 crédit.'), django.core.validators.MaxValueValidator(6, message='Les crédits ne peuvent pas dépasser 6.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EDT_app.matiere')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EDT_app.semestre')),
            ],
            options={
                'unique_together': {('libelle', 'semestre')},
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(editable=False, max_length=100)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='EDT_app.anneeacademique')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EDT_app.filiere')),
                ('parcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EDT_app.parcours')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EDT_app.semestre')),
            ],
            options={
                'unique_together': {('parcours', 'filiere', 'semestre', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=100)),
                ('date_seance', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('type_seance', models.CharField(choices=[('CM', 'Cours Magistral'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques')], max_length=5)),
                ('statut', models.CharField(choices=[('Confirmée', 'Confirmée'), ('Annulée', 'Annulée'), ('Reportée', 'Reportée')], default='Confirmée', max_length=20)),
                ('date_report', models.DateField(blank=True, help_text='Obligatoire si la séance est reportée.', null=True)),
                ('heure_debut_report', models.TimeField(blank=True, help_text='Heure de début du créneau de report. Fixe à 09h00.', null=True)),
                ('heure_fin_report', models.TimeField(blank=True, help_text='Heure de fin du créneau de report.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EDT_app.anneeacademique')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EDT_app.classe')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EDT_app.module')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EDT_app.enseignant')),
            ],
        ),
        migrations.AddField(
            model_name='enseignant',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EDT_app.departement'),
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='EDT_app.profil')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EDT_app.classe')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EDT_app.filiere')),
                ('parcours', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EDT_app.parcours')),
            ],
        ),
    ]
