# Generated by Django 6.0.2 on 2026-05-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDT_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='seance',
            name='date_report',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seance',
            name='heure_debut_report',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seance',
            name='heure_fin_report',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seance',
            name='type_seance',
            field=models.CharField(choices=[('CM', 'CM'), ('TD', 'TD'), ('TP', 'TP')], max_length=5),
        ),
    ]
