# Generated by Django 6.0.2 on 2026-07-28 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDT_app', '0002_remove_seance_created_at_remove_seance_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferentClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classe',
            name='code',
            field=models.CharField(blank=True, help_text='Code libre pour les classes sans filière (ex: MIP, BCG, PCG).', max_length=20),
        ),
        migrations.AddField(
            model_name='departement',
            name='chef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_diriges', to='EDT_app.enseignant'),
        ),
        migrations.AddField(
            model_name='seance',
            name='seance_liee',
            field=models.ForeignKey(blank=True, help_text='Séance jumelle pour un cours mutualisé (même créneau, classe différente).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances_associees', to='EDT_app.seance'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EDT_app.filiere'),
        ),
        migrations.AddConstraint(
            model_name='classe',
            constraint=models.UniqueConstraint(condition=models.Q(('filiere__isnull', False)), fields=('parcours', 'filiere', 'semestre', 'annee'), name='unique_classe_avec_filiere'),
        ),
        migrations.AddConstraint(
            model_name='classe',
            constraint=models.UniqueConstraint(condition=models.Q(('filiere__isnull', True)), fields=('parcours', 'code', 'semestre', 'annee'), name='unique_classe_sans_filiere'),
        ),
        migrations.AddField(
            model_name='referentclasse',
            name='classes',
            field=models.ManyToManyField(blank=True, help_text="Classes dont cet enseignant peut gérer l'emploi du temps.", related_name='referents', to='EDT_app.classe'),
        ),
        migrations.AddField(
            model_name='referentclasse',
            name='enseignant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referent_classes', to='EDT_app.enseignant'),
        ),
    ]
