# Generated by Django 6.0.2 on 2026-08-06 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDT_app', '0004_profil_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EDT_app.filiere'),
        ),
    ]
