# Generated by Django 6.0.2 on 2026-08-07 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDT_app', '0005_alter_etudiant_filiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filieres_dirigees', to='EDT_app.enseignant'),
        ),
    ]
