# Generated by Django 6.0.2 on 2026-08-19 07:24

import EDT_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDT_app', '0006_filiere_responsable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/', validators=[EDT_app.models.validate_extension_fichier])),
                ('type_doc', models.CharField(choices=[('cours', 'Cours'), ('td', 'TD'), ('tp', 'TP'), ('examen', 'Examen'), ('autre', 'Autre')], default='cours', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='EDT_app.enseignant')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='EDT_app.module')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
