# Generated by Django 6.0.2 on 2026-08-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDT_app', '0007_documentpedagogique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpedagogique',
            name='type_doc',
            field=models.CharField(choices=[('cours', 'Cours'), ('td', 'TD'), ('tp', 'TP'), ('autre', 'Autre')], default='cours', max_length=20),
        ),
    ]
