# Generated by Django 6.0.2 on 2026-08-22 22:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDT_app', '0008_alter_documentpedagogique_type_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='heures_cm',
            field=models.IntegerField(blank=True, help_text='Volume horaire CM prévu. Optionnel.', null=True, validators=[django.core.validators.MinValueValidator(0, message='Les heures CM ne peuvent pas être négatives.')]),
        ),
        migrations.AddField(
            model_name='module',
            name='heures_td',
            field=models.IntegerField(blank=True, help_text='Volume horaire TD prévu. Optionnel.', null=True, validators=[django.core.validators.MinValueValidator(0, message='Les heures TD ne peuvent pas être négatives.')]),
        ),
        migrations.AddField(
            model_name='module',
            name='heures_tp',
            field=models.IntegerField(blank=True, help_text='Volume horaire TP prévu. Optionnel.', null=True, validators=[django.core.validators.MinValueValidator(0, message='Les heures TP ne peuvent pas être négatives.')]),
        ),
        migrations.CreateModel(
            name='AffectationModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_seance', models.CharField(blank=True, choices=[('CM', 'CM'), ('TD', 'TD'), ('TP', 'TP')], help_text='Laisser vide pour une affectation générique (tous types).', max_length=5, null=True)),
                ('heures_prevues', models.FloatField(help_text='Volume horaire affecté à cet enseignant pour ce module (et ce type).', validators=[django.core.validators.MinValueValidator(0, message='Le volume prévu ne peut pas être négatif.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='EDT_app.enseignant')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='EDT_app.module')),
            ],
            options={
                'ordering': ['module', 'enseignant', 'type_seance'],
                'constraints': [models.UniqueConstraint(fields=('module', 'enseignant', 'type_seance'), name='unique_affectation_module_enseignant_type')],
            },
        ),
    ]
