# Generated by Django 6.0.2 on 2026-08-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDT_app', '0009_affectation_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('Confirmée', 'Confirmée'), ('Annulée', 'Annulée'), ('Reportée', 'Reportée')], default='brouillon', max_length=20),
        ),
    ]
