# Generated by Django 6.0.2 on 2026-08-29 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDT_app', '0010_alter_seance_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='EDT_app.classe'),
        ),
    ]
