# Generated by Django 6.0.2 on 2026-09-03 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EDT_app', '0011_module_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='filiere',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='parcours',
        ),
    ]
