# Generated by Django 6.0.2 on 2026-09-07 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDT_app', '0012_remove_etudiant_filiere_remove_etudiant_parcours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='code',
            field=models.CharField(blank=True, help_text='Code libre pour les classes sans filière (ex: MIP, BGC, PCG).', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('libelle', 'semestre', 'classe')},
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_inscription', models.CharField(choices=[('Inscription', 'Inscription'), ('Réinscription', 'Réinscription')], max_length=15)),
                ('date_inscription', models.DateField()),
                ('statut', models.CharField(choices=[('active', 'Active'), ('terminée', 'Terminée'), ('abandonnée', 'Abandonnée')], default='active', max_length=12)),
                ('reference_externe', models.CharField(blank=True, db_index=True, help_text="Identifiant de l'inscription dans l'application de scolarité.", max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='EDT_app.anneeacademique')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='EDT_app.classe')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='EDT_app.etudiant')),
            ],
            options={
                'ordering': ['-annee__date_debut', 'classe'],
                'constraints': [models.UniqueConstraint(fields=('etudiant', 'classe'), name='unique_inscription_etudiant_classe')],
            },
        ),
    ]
