# Generated by Django 6.0.2 on 2026-09-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDT_app', '0013_alter_classe_code_alter_module_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationmodule',
            name='hors_departement',
            field=models.BooleanField(blank=True, default=False, help_text="Coché quand ce module est affecté par un chef qui ne dirige pas le département propriétaire de la matière (intervention inter-départements, ex : un module de Mathématiques enseigné dans une classe d'Informatique)."),
        ),
    ]
