# Generated by Django 6.0.2 on 2026-09-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDT_app', '0014_affectationmodule_hors_departement'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='seance',
            index=models.Index(fields=['enseignant', 'date_seance', 'statut'], name='EDT_app_sea_enseign_82b0fc_idx'),
        ),
        migrations.AddIndex(
            model_name='seance',
            index=models.Index(fields=['classe', 'date_seance', 'statut'], name='EDT_app_sea_classe__d8110e_idx'),
        ),
    ]
