# Generated by Django 6.0.8 on 2026-10-01 19:59

import EDT_app.models
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDT_app', '0015_seance_conflit_indexes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='affectationmodule',
            name='unique_affectation_module_enseignant_type',
        ),
        migrations.RemoveConstraint(
            model_name='classe',
            name='unique_classe_avec_filiere',
        ),
        migrations.RemoveConstraint(
            model_name='classe',
            name='unique_classe_sans_filiere',
        ),
        migrations.AlterField(
            model_name='anneeacademique',
            name='libelle',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='documentpedagogique',
            name='fichier',
            field=models.FileField(max_length=255, upload_to=EDT_app.models.chemin_document, validators=[EDT_app.models.validate_extension_fichier]),
        ),
        migrations.AlterField(
            model_name='profil',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=EDT_app.models.chemin_photo),
        ),
        migrations.AddConstraint(
            model_name='affectationmodule',
            constraint=models.UniqueConstraint(models.F('module'), models.F('enseignant'), django.db.models.functions.comparison.Coalesce(models.F('type_seance'), models.Value('')), name='unique_affectation_module_enseignant_type'),
        ),
        migrations.AddConstraint(
            model_name='classe',
            constraint=models.UniqueConstraint(fields=('parcours', 'filiere', 'semestre', 'annee'), name='unique_classe_avec_filiere'),
        ),
        migrations.AddConstraint(
            model_name='classe',
            constraint=models.UniqueConstraint(models.F('parcours'), models.F('semestre'), models.F('annee'), models.Case(models.When(filiere__isnull=True, then=models.F('code')), default=models.Value(None), output_field=models.CharField(max_length=20)), name='unique_classe_sans_filiere'),
        ),
    ]
